# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Prepare to run parity
          command: |
            mkdir -p /tmp/parity/keys
            cp -r tests/parity-keys /tmp/parity/keys/DevelopmentChain
            cp tests/parity-dev.json /tmp/parity
            cp tests/parity-dev.pwds /tmp/parity
            chmod -R 777 /tmp/parity

      - run: ls -la /tmp/parity

      - run:
          name: Starting Parity
          command: docker run -d -p 8545:8545 -p 8546:8546 -p 30303:30303 -p 30303:30303/udp --name parity -v /tmp/parity:/home/parity/.local/share/io.parity.ethereum parity/parity:v2.4.8-stable --chain /home/parity/.local/share/io.parity.ethereum/parity-dev.json --unlock=0x7454a8F5a7c7555d79B172C89D20E1f4e4CC226C --password /home/parity/.local/share/io.parity.ethereum/parity-dev.pwds --min-gas-price 1000000000 --jsonrpc-interface all

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Waiting for Parity to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z localhost 8545 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            docker ps -a
            docker logs parity 
            echo Failed waiting for Parity && exit 1

      # run tests!
      - run:
          name: run tests
          command: |
           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
           [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
           nvm install 10.15.3
           node -v
           npm test
           date
